-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, 
ROUND(A.DAILY_FEE * 30 * (100 - REPLACE(C.DISCOUNT_RATE, '%', '')) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON A.CAR_TYPE = C.CAR_TYPE

WHERE A.CAR_TYPE IN ('SUV', '세단')
AND C.DURATION_TYPE = '30일 이상'
AND A.CAR_ID NOT IN (
SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
AND ROUND(A.DAILY_FEE * 30 * (100 - REPLACE(C.DISCOUNT_RATE, '%', '')) / 100) >= 500000
AND ROUND(A.DAILY_FEE * 30 * (100 - REPLACE(C.DISCOUNT_RATE, '%', '')) / 100) < 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;